---
version: 2.1

executors:
  debian:
    docker:
    - image: debian:bookworm
  ruby:
    docker:
    - image: circleci/ruby:latest

jobs:
  build:
    executor: debian

    steps:
    - run: apt-get update
    # We need to install the FOSDEM repo for the pythonosc lib
    - run: apt-get install -y debian-archive-keyring
    - run: apt-get install -y gnupg curl ca-certificates apt-transport-https
    - run: mkdir -p /etc/apt/keyrings/
    - run: curl -fsSL https://packagecloud.io/fosdem/video-team/gpgkey | gpg --dearmor > /etc/apt/keyrings/fosdem_video-team-archive-keyring.gpg
    - run: mkdir -p /etc/apt/sources.list.d/
    - run: echo "deb [signed-by=/etc/apt/keyrings/fosdem_video-team-archive-keyring.gpg] https://packagecloud.io/fosdem/video-team/debian bookworm main" > /etc/apt/sources.list.d/fosdem_video-team.list
    - run: apt-get update
    # And basic build dependencies for all projects
    - run: apt-get -y install build-essential git openssh-client dpkg-dev debhelper dh-python pybuild-plugin-pyproject python3-all python3-setuptools
    - checkout

    # Then build the mixer library
    - run: apt-get -y install python3-serial python3-osc
    - run: cd osc-lib && ../generate_release.sh
    - run: cd osc-lib && make -f debian/rules binary
    # For the CLI, we have to install its build dependencies
    - run: apt-get -y install python3-click python3-click-repl python3-tabulate
    - run: cd cli && ../generate_release.sh
    - run: cd cli && make -f debian/rules binary

    # Finally, we move the .deb files to the build artifacts
    - run: mkdir -p /root/build
    - run: mv ./*.deb /root/build
    - persist_to_workspace:
        root: /root/build
        paths:
        - .
    - store_artifacts:
        path: /root/build

  package:
    executor: ruby

    steps:
    - attach_workspace:
        at: .
    - run: gem install package_cloud
    - run: find .
    - run: package_cloud push fosdem/video-team/debian/bookworm *deb

workflows:
  version: 2
  python-fosdemosc:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - package:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
